name: Build Windows EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Installa dipendenze
      run: |
        pip install pyinstaller customtkinter Pillow packaging

    - name: Genera Eseguibile
      shell: pwsh
      run: |
        # Recupera il percorso della libreria customtkinter dinamicamente
        $ctk_path = python -c "import customtkinter; import os; print(os.path.dirname(customtkinter.__file__))"
        
        pyinstaller --noconsole --onefile `
        --add-data "${ctk_path};customtkinter/" `
        --icon="iconaVTI.ico" `
        --name "VTI" `
        vti_app.py

    - name: Archivia Risultato
      uses: actions/upload-artifact@v4
      with:
        name: VTI-Windows-Exe
        path: dist/VTI.exe
